import json
import sys
import tempfile
import unittest
import zipfile
from pathlib import Path
from unittest.mock import patch

from orca_plugin.common import OrcaError, sha256, write_json
from orca_plugin.preview import layer_svg
from orca_plugin.profiles import Catalog, inspect_project, validate_changes
from orca_plugin.slicer import Slicer


GCODE = '''; generated by OrcaSlicer
; curr_bed_type = Textured PEI Plate
; nozzle_diameter = 0.4
; filament_type = PLA
; nozzle_temperature = 220
; nozzle_temperature_initial_layer = 220
; textured_plate_temp = 55
; first_layer_bed_temperature = 55
; estimated printing time (normal mode) = 1m 2s
; total filament used [g] = 0.25
G90
M82
G92 E0
; CHANGE_LAYER
G1 X10 Y10 Z0.2
G1 X20 Y10 E1
G1 X20 Y20 E2
; CHANGE_LAYER
G1 X10 Y20 E3
'''


class Base(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.base = Path(self.tmp.name)

    def project(self, **settings):
        path = self.base / "source.3mf"
        d = {"printer_settings_id": "Example 0.4 nozzle", "nozzle_diameter": ["0.4"], "layer_height": "0.2"}
        d.update(settings)
        with zipfile.ZipFile(path, "w") as z:
            z.writestr("Metadata/project_settings.config", json.dumps(d))
            z.writestr("Metadata/model_settings.config", '<config><object id="1"><metadata key="name" value="cube"/><metadata key="wall_loops" value="5"/></object></config>')
        return path

    def sliced(self):
        s = Slicer(self.base)
        d = self.base / "jobs" / "job1"
        d.mkdir(parents=True)
        gcode = d / "plate.gcode"
        gcode.write_text(GCODE)
        write_json(d / "job.json", {"id": "job1", "state": "sliced", "printer_profile": "Example 0.4 nozzle",
                                  "artifacts": [{"name": gcode.name, "path": str(gcode), "sha256": sha256(gcode)}]})
        return s, gcode


class ProfilesTests(Base):
    def test_cycle_and_missing_parent(self):
        for name, parent in (("a", "b"), ("b", "a")):
            write_json(self.base / f"{name}.json", {"type": "process", "name": name, "inherits": parent})
        with self.assertRaisesRegex(OrcaError, "cycle"):
            Catalog([self.base]).resolve(self.base / "a.json", "process")
        (self.base / "b.json").unlink()
        with self.assertRaisesRegex(OrcaError, "Missing"):
            Catalog([self.base]).resolve(self.base / "a.json", "process")

    def test_same_named_bases_are_vendor_scoped(self):
        for vendor, diameter in (("A", "0.4"), ("B", "0.6")):
            directory = self.base / vendor / "machine"
            write_json(directory / "base.json", {"type": "machine", "name": "common", "nozzle_diameter": [diameter]})
            write_json(directory / "child.json", {"type": "machine", "name": vendor + " printer", "inherits": "common"})
        catalog = Catalog([self.base])
        for vendor, diameter in (("A", "0.4"), ("B", "0.6")):
            self.assertEqual(catalog.resolve(self.base / vendor / "machine/child.json", "machine")["nozzle_diameter"], [diameter])

    def test_bounds_and_no_arbitrary_gcode(self):
        for changes in ({"layer_height": "nan"}, {"wall_loops": 2.5}, {"sparse_infill_density": 101}, {"machine_start_gcode": "M112"}):
            with self.subTest(changes=changes), self.assertRaises(OrcaError):
                validate_changes(changes)
        self.assertEqual(validate_changes({"sparse_infill_density": "15%"}), {"sparse_infill_density": "15%"})

    @patch("orca_plugin.slicer.discover", return_value=Path(sys.executable))
    def test_prepare_preserves_source_and_object_overrides(self, _):
        src = self.project()
        before = src.read_bytes()
        from tests.tools_harness import Tools
        tools = Tools(self.base)
        self.assertIn("bed_type", tools.reject("orca_prepare", source=str(src), bed_type="not a plate"))
        job = tools.call("orca_prepare", source=str(src), changes={"layer_height": 0.24}, bed_type="Textured PEI Plate")
        self.assertEqual(src.read_bytes(), before)
        report = inspect_project(job["input"])
        self.assertEqual(report["settings"]["layer_height"], "0.24")
        self.assertEqual(report["settings"]["curr_bed_type"], "Textured PEI Plate")
        self.assertEqual(report["objects"][0]["settings"]["wall_loops"], "5")

    @patch("orca_plugin.slicer.discover", return_value=Path(sys.executable))
    def test_nozzle_mismatch_and_raw_without_presets(self, _):
        with self.assertRaisesRegex(OrcaError, "80%"):
            Slicer(self.base).prepare(str(self.project()), {"layer_height": 0.4})
        stl = self.base / "cube.stl"
        stl.write_text("solid cube\nendsolid cube")
        with self.assertRaisesRegex(OrcaError, "require"):
            Slicer(self.base).prepare(str(stl))


class JobTests(Base):
    def test_artifact_tampering_and_export_no_overwrite(self):
        s, gcode = self.sliced()
        destination = self.base / "export.gcode"
        result = s.export("job1", "plate.gcode", str(destination))
        self.assertFalse(result["print_started"])
        with self.assertRaisesRegex(OrcaError, "already exists"):
            s.export("job1", "plate.gcode", str(destination))
        gcode.write_text("tampered")
        with self.assertRaisesRegex(OrcaError, "changed"):
            s.artifact("job1", "plate.gcode")

    def test_path_traversal(self):
        s, _ = self.sliced()
        with self.assertRaises(OrcaError):
            s.job("../../etc")
        with self.assertRaises(OrcaError):
            s.artifact("job1", "../../secret")

    def test_preview_relative_extrusion_and_arcs(self):
        _, gcode = self.sliced()
        result = layer_svg(gcode, self.base / "preview.svg")
        self.assertEqual(result["segments"], 2)
        self.assertEqual(result["extrusion_xy_bounds"], [10, 10, 20, 20])
        gcode.write_text(GCODE.replace("M82", "M83").replace("G1 X20 Y20 E2", "G2 X20 Y20 E2 I0 J5"))
        result = layer_svg(gcode, self.base / "preview2.svg")
        self.assertIn("G2/G3 arcs omitted", result["warnings"])

    def test_slicer_failed_exit_never_printable(self):
        s, _ = self.sliced()
        d = s.directory("job1")
        s._run(d, [sys.executable, "-c", "raise SystemExit(3)"])
        self.assertEqual(s.job("job1")["state"], "failed")
        with self.assertRaises(OrcaError):
            s.artifact("job1", "plate.gcode")

    def test_completed_worker_extracts_archive_without_zip_paths(self):
        s, _ = self.sliced()
        d = s.directory("job1")
        (d / "output").mkdir()
        with zipfile.ZipFile(d / "output/sliced.3mf", "w") as z:
            z.writestr("../../outside.gcode", GCODE)
        s._run(d, [sys.executable, "-c", "pass"])
        self.assertEqual(s.job("job1")["state"], "sliced")
        self.assertFalse((self.base / "outside.gcode").exists())
        self.assertEqual(len(s.job("job1")["reports"]), 1)


if __name__ == "__main__":
    unittest.main()
