import importlib.util
import json
import os
import subprocess
import sys
import tempfile
import threading
import time
import unittest
import zipfile
from pathlib import Path
from unittest.mock import patch
from unittest.mock import Mock
import io
import urllib.error

from orca_plugin import Service, TOOLS, register
from orca_plugin.common import OrcaError, sha256, write_json
from orca_plugin.preview import layer_svg
from orca_plugin.printers import Printers, Moonraker, OctoPrint, HTTP
from orca_plugin.profiles import Catalog, inspect_project, validate_changes
from orca_plugin.slicer import Slicer, analyze_gcode


GCODE = '''; generated by OrcaSlicer
; estimated printing time (normal mode) = 1m 2s
; total filament used [g] = 0.25
G90
M82
G92 E0
; CHANGE_LAYER
G1 X10 Y10 Z0.2
G1 X20 Y10 E1
G1 X20 Y20 E2
; CHANGE_LAYER
G1 X10 Y20 E3
'''


class Base(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.base = Path(self.tmp.name)

    def project(self, **settings):
        path = self.base / "source.3mf"
        d = {"printer_settings_id": "Example 0.4 nozzle", "nozzle_diameter": ["0.4"], "layer_height": "0.2"}
        d.update(settings)
        with zipfile.ZipFile(path, "w") as z:
            z.writestr("Metadata/project_settings.config", json.dumps(d))
            z.writestr("Metadata/model_settings.config", '<config><object id="1"><metadata key="name" value="cube"/><metadata key="wall_loops" value="5"/></object></config>')
        return path

    def sliced(self):
        s = Slicer(self.base)
        d = self.base / "jobs" / "job1"
        d.mkdir(parents=True)
        gcode = d / "plate.gcode"
        gcode.write_text(GCODE)
        write_json(d / "job.json", {"id": "job1", "state": "sliced", "printer_profile": "Example 0.4 nozzle",
                                  "artifacts": [{"name": gcode.name, "path": str(gcode), "sha256": sha256(gcode)}]})
        return s, gcode


class ProfilesTests(Base):
    def test_inheritance_and_user_override(self):
        write_json(self.base / "base.json", {"type": "machine", "name": "base", "layer_height": "0.2", "nozzle_diameter": ["0.4"]})
        write_json(self.base / "child.json", {"type": "machine", "name": "child", "inherits": "base", "layer_height": "0.16"})
        c = Catalog([self.base])
        d = c.resolve(self.base / "child.json", "machine")
        self.assertEqual(d["nozzle_diameter"], ["0.4"])
        self.assertEqual(d["layer_height"], "0.16")
        self.assertNotIn("inherits", d)

    def test_cycle_and_missing_parent(self):
        for name, parent in (("a", "b"), ("b", "a")):
            write_json(self.base / f"{name}.json", {"type": "process", "name": name, "inherits": parent})
        with self.assertRaisesRegex(OrcaError, "cycle"):
            Catalog([self.base]).resolve(self.base / "a.json", "process")
        (self.base / "b.json").unlink()
        with self.assertRaisesRegex(OrcaError, "Missing"):
            Catalog([self.base]).resolve(self.base / "a.json", "process")

    def test_same_named_bases_are_vendor_scoped(self):
        for vendor, diameter in (("A", "0.4"), ("B", "0.6")):
            directory = self.base / vendor / "machine"
            write_json(directory / "base.json", {"type": "machine", "name": "common", "nozzle_diameter": [diameter]})
            write_json(directory / "child.json", {"type": "machine", "name": vendor + " printer", "inherits": "common"})
        catalog = Catalog([self.base])
        for vendor, diameter in (("A", "0.4"), ("B", "0.6")):
            self.assertEqual(catalog.resolve(self.base / vendor / "machine/child.json", "machine")["nozzle_diameter"], [diameter])

    @patch("orca_plugin.slicer.discover", return_value=Path(sys.executable))
    def test_concrete_profile_name_replaces_inherited_generic_id(self, _):
        files = {}
        for kind, data in {
            "machine": {"name": "Actual printer 0.4", "printer_settings_id": "Generic", "nozzle_diameter": ["0.4"]},
            "process": {"name": "Standard", "compatible_printers": ["Actual printer 0.4"], "layer_height": "0.2"},
            "filament": {"name": "PLA", "compatible_printers": ["Actual printer 0.4"]},
        }.items():
            path = self.base / f"{kind}.json"
            write_json(path, dict(type=kind, **data))
            files[kind] = str(path)
        stl = self.base / "cube.stl"
        stl.write_text("solid cube\nendsolid cube")
        result = Slicer(self.base).prepare(str(stl), machine=files["machine"], process=files["process"], filaments=[files["filament"]])
        self.assertEqual(result["printer_profile"], "Actual printer 0.4")

    def test_bounds_and_no_arbitrary_gcode(self):
        for changes in ({"layer_height": "nan"}, {"wall_loops": 2.5}, {"sparse_infill_density": 101}, {"machine_start_gcode": "M112"}):
            with self.subTest(changes=changes), self.assertRaises(OrcaError):
                validate_changes(changes)
        self.assertEqual(validate_changes({"sparse_infill_density": "15%"}), {"sparse_infill_density": "15%"})

    @patch("orca_plugin.slicer.discover", return_value=Path(sys.executable))
    def test_prepare_preserves_source_and_object_overrides(self, _):
        src = self.project()
        before = src.read_bytes()
        job = Slicer(self.base).prepare(str(src), {"layer_height": 0.24})
        self.assertEqual(src.read_bytes(), before)
        report = inspect_project(job["input"])
        self.assertEqual(report["settings"]["layer_height"], "0.24")
        self.assertEqual(report["objects"][0]["settings"]["wall_loops"], "5")

    @patch("orca_plugin.slicer.discover", return_value=Path(sys.executable))
    def test_nozzle_mismatch_and_raw_without_presets(self, _):
        with self.assertRaisesRegex(OrcaError, "80%"):
            Slicer(self.base).prepare(str(self.project()), {"layer_height": 0.4})
        stl = self.base / "cube.stl"
        stl.write_text("solid cube\nendsolid cube")
        with self.assertRaisesRegex(OrcaError, "require"):
            Slicer(self.base).prepare(str(stl))


class JobTests(Base):
    def test_artifact_tampering_and_export_no_overwrite(self):
        s, gcode = self.sliced()
        destination = self.base / "export.gcode"
        result = s.export("job1", "plate.gcode", str(destination))
        self.assertFalse(result["print_started"])
        with self.assertRaisesRegex(OrcaError, "already exists"):
            s.export("job1", "plate.gcode", str(destination))
        gcode.write_text("tampered")
        with self.assertRaisesRegex(OrcaError, "changed"):
            s.artifact("job1", "plate.gcode")

    def test_path_traversal(self):
        s, _ = self.sliced()
        with self.assertRaises(OrcaError):
            s.job("../../etc")
        with self.assertRaises(OrcaError):
            s.artifact("job1", "../../secret")

    def test_preview_relative_extrusion_and_arcs(self):
        _, gcode = self.sliced()
        result = layer_svg(gcode, self.base / "preview.svg")
        self.assertEqual(result["segments"], 2)
        self.assertEqual(result["extrusion_xy_bounds"], [10, 10, 20, 20])
        gcode.write_text(GCODE.replace("M82", "M83").replace("G1 X20 Y20 E2", "G2 X20 Y20 E2 I0 J5"))
        result = layer_svg(gcode, self.base / "preview2.svg")
        self.assertIn("G2/G3 arcs omitted", result["warnings"])

    def test_slicer_failed_exit_never_printable(self):
        s, _ = self.sliced()
        d = s.directory("job1")
        s._run(d, [sys.executable, "-c", "raise SystemExit(3)"])
        self.assertEqual(s.job("job1")["state"], "failed")
        with self.assertRaises(OrcaError):
            s.artifact("job1", "plate.gcode")

    def test_completed_worker_extracts_archive_without_zip_paths(self):
        s, _ = self.sliced()
        d = s.directory("job1")
        (d / "output").mkdir()
        with zipfile.ZipFile(d / "output/sliced.3mf", "w") as z:
            z.writestr("../../outside.gcode", GCODE)
        s._run(d, [sys.executable, "-c", "pass"])
        self.assertEqual(s.job("job1")["state"], "sliced")
        self.assertFalse((self.base / "outside.gcode").exists())
        self.assertEqual(len(s.job("job1")["reports"]), 1)


class FakeHTTP:
    calls = []
    fail_start = False
    busy = False

    def __init__(self, config):
        self.config = config

    def request(self, method, path, data=None):
        self.calls.append((method, path, data))
        if path.startswith("/printer/objects"):
            return {"result": {"status": {"print_stats": {"state": "printing" if self.busy else "standby"}, "webhooks": {"state": "ready"}}}}
        if path == "/api/printer":
            return {"state": {"flags": {"operational": True, "printing": self.busy}}}
        if path == "/api/job" and method == "GET":
            return {"state": "Operational"}
        if self.fail_start:
            raise OrcaError("Printer request failed or timed out.")
        return {}

    def upload(self, endpoint, path, filename, fields):
        self.calls.append(("UPLOAD", endpoint, fields))
        if endpoint == "/server/files/upload":
            return {"item": {"path": filename}, "print_started": False}
        return {"files": {"local": {"path": filename}}}


class PrinterTests(Base):
    def setUp(self):
        super().setUp()
        FakeHTTP.calls = []
        FakeHTTP.busy = False
        FakeHTTP.fail_start = False
        self.s, self.gcode = self.sliced()
        self.p = Printers(self.base, self.s, FakeHTTP)
        self.p.configure("klipper", "moonraker", "Example 0.4 nozzle", "http://localhost:7125")

    def test_upload_never_starts_and_start_requires_intent(self):
        receipt = self.p.upload("klipper", "job1", "plate.gcode")
        self.assertFalse(receipt["print_started"])
        self.assertFalse(any(c[1] == "/printer/print/start" for c in FakeHTTP.calls))
        with self.assertRaisesRegex(OrcaError, "explicit"):
            self.p.start(receipt["receipt_id"])
        self.assertEqual(self.p.start(receipt["receipt_id"], True)["state"], "start_accepted")
        with self.assertRaisesRegex(OrcaError, "already attempted"):
            self.p.start(receipt["receipt_id"], True)

    def test_uncertain_start_not_retried(self):
        receipt = self.p.upload("klipper", "job1", "plate.gcode")
        FakeHTTP.fail_start = True
        with self.assertRaises(OrcaError):
            self.p.start(receipt["receipt_id"], True)
        FakeHTTP.fail_start = False
        with self.assertRaisesRegex(OrcaError, "already attempted"):
            self.p.start(receipt["receipt_id"], True)
        self.assertEqual(sum(c[1] == "/printer/print/start" for c in FakeHTTP.calls), 1)

    def test_mismatched_profile_and_busy_printer(self):
        self.p.configure("wrong", "moonraker", "Different nozzle", "http://localhost")
        with self.assertRaisesRegex(OrcaError, "does not match"):
            self.p.upload("wrong", "job1", "plate.gcode")
        FakeHTTP.busy = True
        with self.assertRaisesRegex(OrcaError, "busy"):
            self.p.upload("klipper", "job1", "plate.gcode")

    def test_expired_receipt(self):
        r = self.p.upload("klipper", "job1", "plate.gcode")
        with patch("orca_plugin.printers.time.time", return_value=time.time() + 4000):
            with self.assertRaisesRegex(OrcaError, "expired"):
                self.p.start(r["receipt_id"], True)

    def test_octoprint_routes_and_no_upload_start(self):
        self.p.configure("octo", "octoprint", "Example 0.4 nozzle", "http://localhost")
        r = self.p.upload("octo", "job1", "plate.gcode")
        upload = next(c for c in FakeHTTP.calls if c[0] == "UPLOAD")
        self.assertEqual(upload[2], {"select": "false", "print": "false"})
        self.p.start(r["receipt_id"], True)
        self.assertTrue(any(c[0] == "POST" and c[1].startswith("/api/files/local/") and c[2]["print"] is True for c in FakeHTTP.calls))
        self.p.control("octo", "pause", True)
        self.assertEqual(FakeHTTP.calls[-1], ("POST", "/api/job", {"command": "pause", "action": "pause"}))

    def test_bad_urls_and_secrets_not_in_config(self):
        for url in ("file:///etc/passwd", "https://user:password@localhost", "http://localhost/?key=secret"):
            with self.subTest(url=url), self.assertRaises(OrcaError):
                self.p.configure("invalid", "moonraker", "Example", url)
        self.p.configure("authenticated", "octoprint", "Example", "https://localhost", "OCTO_API_KEY")
        self.assertNotIn("api_key", self.p.config("authenticated"))

    def test_file_handoff_is_not_a_fake_network_printer(self):
        self.p.configure("sd", "file", "Any brand")
        self.assertEqual(self.p.status("sd")["state"], "manual_handoff")
        with self.assertRaises(OrcaError):
            self.p.control("sd", "resume", True)


class RegistrationTests(Base):
    def test_tools_match_manifest_and_registration_has_no_io(self):
        class Context:
            tools = {}
            def register_tool(self, **kwargs):
                self.tools[kwargs["name"]] = kwargs
            def register_skill(self, name, path):
                assert path.exists()
        ctx = Context()
        with patch("subprocess.Popen", side_effect=AssertionError("registration must not spawn")):
            register(ctx)
        self.assertEqual(set(ctx.tools), set(TOOLS))
        text = (Path(__file__).parents[1] / "plugin.yaml").read_text()
        for name in TOOLS:
            self.assertIn("  - " + name + "\n", text)

    def test_handlers_return_structured_errors(self):
        s = Service(self.base)
        result = json.loads(s.handle("orca_job", {"job_id": "../secret"}))
        self.assertFalse(result["success"])
        self.assertFalse(json.loads(s.handle("orca_slice", {}))["success"])


class HTTPTests(Base):
    def test_real_request_encoding_and_auth_header(self):
        http = HTTP({"url": "https://printer.example/prefix", "api_key_env": "TEST_ORCA_KEY"})
        response = Mock()
        response.__enter__ = Mock(return_value=response)
        response.__exit__ = Mock(return_value=False)
        response.read.return_value = b'{"ok":true}'
        http.opener = Mock()
        http.opener.open.return_value = response
        path = self.base / "tiny.gcode"
        path.write_text(GCODE)
        with patch.dict(os.environ, {"TEST_ORCA_KEY": "test-secret-not-real"}):
            http.upload("/api/files/local", path, "unique.gcode", {"print": "false"})
        req = http.opener.open.call_args.args[0]
        self.assertEqual(req.full_url, "https://printer.example/prefix/api/files/local")
        self.assertEqual(req.get_header("X-api-key"), "test-secret-not-real")
        self.assertIn(b'name="print"\r\n\r\nfalse', req.data)
        self.assertIn(b'filename="unique.gcode"', req.data)

    def test_server_error_body_does_not_leak(self):
        http = HTTP({"url": "https://printer.example"})
        http.opener = Mock()
        http.opener.open.side_effect = urllib.error.HTTPError("https://printer.example", 401, "secret body", {}, io.BytesIO(b"secret"))
        with self.assertRaises(OrcaError) as ctx:
            http.request("GET", "/api/printer")
        self.assertNotIn("secret", str(ctx.exception))

    def test_redirect_never_forwards_credentials(self):
        from orca_plugin.printers import NoRedirect
        with self.assertRaisesRegex(OrcaError, "redirected"):
            NoRedirect().redirect_request(None, None, 302, "", {}, "https://other.example")


if __name__ == "__main__":
    unittest.main()
